language: python
sudo: false
branches:
  only:
    - master
python:
  - "3.4"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
before_install:
  - pip install -U pip setuptools wheel
install:
  - travis_wait travis_retry pip install -r requirements.txt
#  - travis_retry python setup.py dev
script: 
 - python run_unit_tests.py
 - python run_integration_tests.py
