language: python
python:
  - "3.4"
# command to install dependencies
install:
    - sudo apt-get install -qq python-numpy python-scipy
# command to run tests
script: 
 - python run_unit_tests.py
 - python run_integration_tests.py
