language: python
python:
  - "3.4"
virtualenv:
  system_site_packages: true
# command to install dependencies
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
# command to run tests
script: 
 - python run_unit_tests.py
 - python run_integration_tests.py
