language: python
sudo: false
branches:
  only:
    - master
python:
  - "3.4"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
install:
#  - travis_wait 20 pip install -r requirements.txt > /dev/null
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install python-dateutils
script: 
 - python run_unit_tests.py
 - python run_integration_tests.py
