language: python
sudo: false
branches:
  only:
    - master
python:
  - "3.4"
# addons:
#   apt:
#     packages:
#     - libblas-dev
#     - liblapack-dev
#     - gfortran
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install python-dateutil
script: 
 - python run_unit_tests.py
 - python run_integration_tests.py
